version: '3.9'

services:
  node_app:
    container_name: basic-server
    build:
      context: ./
      dockerfile: ./Dockerfile
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    ports:
      - '3000:3000'
