version: '3.9'

services:
  node_app:
    container_name: basic-server
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - .:/usr/src/app
    ports:
      - '3000:3000'
    restart: 'unless-stopped'
  mongo:
    image: mongo
    container_name: basic-mongodb
    volumes:
      - mongo_data:/data/db
    ports:
      - '27017:27017'
    restart: 'unless-stopped'

volumes:
  mongo_data:
    driver: local
